name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          TURNSTILE_SECRET: ${{ secrets.TURNSTILE_SECRET }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<EOF
          set -e

          cd /home/neo/weather-server

          git fetch origin
          git reset --hard origin/main

          npm ci --omit=dev

          
          touch .env

          grep -Ev '^(OPENWEATHER_API_KEY|TURNSTILE_SECRET)=' .env > .env.tmp || true

          echo "OPENWEATHER_API_KEY=$OPENWEATHER_API_KEY" >> .env.tmp
          echo "TURNSTILE_SECRET=$TURNSTILE_SECRET" >> .env.tmp

          mv .env.tmp .env

          pm2 restart weather-api

          echo "Deployment successful at \$(date)"
          EOF
